In [21]:
#ANN regression model to predict the electrical energy output of a combined cycle power plant
#Importiing the libraries
import pandas as pd
import numpy as np 
import tensorflow as tf

In [22]:
#checking the version of tensorflow
tf.__version__

'2.17.0'

In [23]:
#importing the dataset
dataset= pd.read_excel('/Users/shravann/Downloads/Portfolio db/ML AZ/Folds5x2_pp.xlsx')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [24]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [25]:
#splitting the dataset into training and test sets
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2,random_state=0)

In [27]:
#building the artificial neural networks
ann = tf.keras.models.Sequential()

In [28]:
#building input and hidden layers
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [29]:
#2nd layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [30]:
#output layer
ann.add(tf.keras.layers.Dense(units=1,activation=None))

In [31]:
#training the ann
ann.compile(optimizer='adam', loss='mean_squared_error')

In [32]:
#fitting the ann on the training set
ann.fit(X_train,y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 417us/step - loss: 30810.6641  
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 382us/step - loss: 381.2113
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 380us/step - loss: 351.1790
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 378us/step - loss: 318.0379
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 374us/step - loss: 283.5164
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 374us/step - loss: 247.1376
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step - loss: 208.8785
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 373us/step - loss: 169.4432
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 364us/step - loss: 140.0500
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 365us/step - loss: 106.1944
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 375us/step - loss: 82.9222
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 384us/step - loss: 65.7438
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - loss: 51.7818
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 375us/step - l

In [33]:
# predicting the test set results
y_pred= ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 790us/step
[[430.42 431.23]
 [461.46 460.01]
 [464.95 461.14]
 ...
 [472.21 473.26]
 [438.97 438.  ]
 [458.2  463.28]]
